### ISSUE TITLE
Meta: write tests

### ISSUE THREAD

**Issue by Diwakar-Gupta** [Diwakar-Gupta/attendance-backend#6]

**Comment by Diwakar-Gupta** [comment]
List of items for which test needs to be written.
PS: if you find any of the funciton not being used please flag we can remove those


Url end points
1. [ ] `/attendance/ping/`
2. [ ] `/attendance/ping/`
3. [ ] `/attendance/ping/`
4. [ ] `/attendance/ping/`
5. [ ] `/attendance/ping/`
6. [ ] `/attendance/ping/`
7. [ ] `/attendance/ping/`
8. [ ] `/attendance/ping/` 

Model Student
1. [ ] `attendance.models.Student.can_mark_attendance`
2. [ ] `attendance.models.Student.can_send_notifications`
3. [ ] `attendance.models.Student.get_id_number`
4. [ ] `attendance.models.Student.get_object_with_token`
5. [ ] `attendance.models.Student.get_all_students`
6. [ ] `attendance.models.Student.get_all_attendance`
7. [ ] `attendance.models.Student.get_aggregated_attendance` **Priority**


Model SubjectClass
1. [ ] `attendance.models.SubjectClass.get_all_students_attendance_status` **Priority**
2. [ ] `attendance.models.SubjectClass.get_current_class` **Priority**
3. [ ] `attendance.models.SubjectClass.get_classes_for`
4. [ ] `attendance.models.SubjectClass.is_in_attendance_window` **Priority**
5. [ ] `attendance.models.SubjectClass.get_all_attendance` **Priority**
6. [ ] `attendance.models.SubjectClass.get_all_classes`


Model ClassAttendance
1. [ ] `attendance.models.ClassAttendance.get_attendance_status_for` **Priority**
4. [ ] `attendance.models.ClassAttendance.get_attendance_status_by_status` 
5. [ ] `attendance.models.ClassAttendance.update_attendance_status`

Model ClassAttendanceWithGeoLocation
1. [ ] `attendance.models.ClassAttendanceWithGeoLocation.get_attendance_status`
2. [ ] `attendance.models.ClassAttendanceWithGeoLocation.create_with`

Model ClassAttendanceByBSM
1. [ ] `attendance.models.ClassAttendanceByBSM.get_attendance_status`
2. [ ] `attendance.models.ClassAttendanceByBSM.create_with`
